name: cog
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - typing
  - pyyaml==6.0
  - datasets==2.6.1
  - elasticsearch==7.13.0
  - faiss-gpu==1.7.2
  - ijson==3.1.4
  - joblib==1.0.1
  - nltk==3.6.2
  - numpy
  - requests==2.25.1
  - scipy==1.7.3
  - tqdm==4.62.3
  - transformers==4.24.0
  - tensorboard
  - shyaml
  - xlrd==2.0.1
  - xlwt==1.3.0
  - pip
  - spacy
  - pynvml
  - jieba
  - ipdb
  - nanopq